include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    # Style
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - sort_pub_dependencies

    # Spayz DS conventions
    - use_decorated_box         # prefer DecoratedBox over Container(decoration:)
    - sized_box_for_whitespace  # prefer SizedBox over Container with only sizing
    - avoid_unnecessary_containers
